function firstStart()
% cd(mainDirectory);
mainDirectory = cd;
path(pathdef,genpath(mainDirectory));
% rename_ref_to_dat
FileLocations = struct(...
    'data', [mainDirectory, '\data\'],...
    'mapping', [mainDirectory, '\data\mapping\'],...
    'gui_files', [mainDirectory, '\imscroll\gui_files\']...
    );
save([mainDirectory, '\imscroll\gui_files\filelocations.dat'], 'FileLocations');
end
