function firstStart(mainDirectory)
cd(mainDirectory);
path(pathdef,genpath(mainDirectory));
rename_ref_to_dat
FileLocations = struct(...
    'data', [mainDirectory, '\data\'],...
    'mapping', [mainDirectory, '\data\mapping\'],...
    'gui_files', [mainDirectory, '\figfiles\imscroll\gui_files\']...
    );
save([mainDirectory, '\figfiles\imscroll\gui_files\filelocations.dat'], FileLocations);
end
