function tests = testGaussFitting
tests = functiontests(localfunctions);
end

function testFitAoisTo2dGaussian(testCase)
% This only tests for tracking is on
loaded = load('imscroll/test/test_data/L2_gauss_test_param.mat');
aoiProcessParameters = struct(...
    'frameAverage', 1,...
    'frameRange', 1:20 ...
);
isTrackAOI = true;

data = fitAoisTo2dGaussian(...
        loaded.aoiinfo,...
        aoiProcessParameters,...
        loaded.imageFileProperty,...
        isTrackAOI...
        );
right_ans = load('imscroll/test/test_data/L2_driftfit_20f_track_avg1.dat', '-mat');
verifyEqual(testCase, data, right_ans.aoifits.data)

end